### PR TITLE
Logical heading structure

### PR DESCRIPTION
**Pull request by laoneo**
For the release details page it would be nice to have a heading structure without skipped levels. With this pr we have:
h1 heading
h2 Release title
h3 Release items

### CODE REVIEW

**Comment by nikosdion** [comment]
I prefer avoiding h1 and h2. In any templates h1 is the site name and h2 is the page / component title. I'd prefer it if `release.blade.php` used an h3 and `item.blade.php` remained on h4. Far less headaches that way.

Thoughts?

**Comment by laoneo** [comment]
As long as it is an order I'm fine. So you want to change this here https://github.com/akeeba/release-system/blob/development/component/frontend/ViewTemplates/Items/default.blade.php#L42 to h2?

**Comment by nikosdion** [comment]
No, set that to **h3** and and revert the `item.blade.php` change. This will get them to the proper h3/h4 order.

**Comment by laoneo** [comment]
Done, but which part is now creating the h1/h2 tags?

**Comment by laoneo** [comment]
In none FOF components the component default.php sets the page heading which is h1, then the component creates the title from the item with h2 and the rest goes then either h2 or h3. But all is rendered within the component. I can't really find it in ars.

**Comment by nikosdion** [comment]
Okay, let me explain this a bit better.

The site's _template_ is responsible for the `<h1>` tags. These are typically used to render the site's name / logo at the top of the page. This makes `<h1>` pretty much forbidden in our components.

If there is a page title the _template_ will render it as an `<h2>`. So, `<h2>` should also not be used by our components.

This leaves us with levels `<h3>` to `<h6>`. That's all we can safely use in our components.

Otherwise we end trying to figure out in our component if there's a page title or not, if the template renders something or not (which may or may not be affected by whether there is a page / component title...) etc. We'd descend into madness. It's much better to end up in a situation where a page has an h1 and then goes to h3 rather than trying to figure out if we should or shouldn't use an h2.

If you are really so worried about h2 vs h3 (I don't see any practical reason but, hey, it's your site...) you can always create template overrides and descend into madness in a way that's specific to your site and your site only.

**Comment by nikosdion** [comment]
For what it's worth, your PR still uses h2/h3 instead of h3/h4. So I am not going to accept it as-is.

**Comment by laoneo** [comment]
Ok, lets close

**Pull request closed without merging**
